services:
  whatsapp:
    build: .
    container_name: whatsapp-bot
    working_dir: /workspace
    stdin_open: true
    tty: true
    shm_size: '2gb'
    restart: unless-stopped

    volumes:
      - .:/workspace
      - /workspace/node_modules
      - ./.wwebjs_auth:/workspace/.wwebjs_auth
      - ./camiones:/workspace/camiones

    environment:
      NODE_ENV: development
      CACHE_DIR: /workspace/camiones

    develop:
      watch:
        - action: sync
          path: .
          target: /workspace
          ignore:
            - node_modules
            - .wwebjs_auth
            - .wwebjs_cache
            - camiones

    command: pnpm start
