services:
  whatsapp:
    build: .
    container_name: whatsapp-bot
    working_dir: /workspace

    stdin_open: true
    tty: true

    shm_size: "2gb"

    volumes:
      - .:/workspace
      - /workspace/node_modules   # evita que el bind mount pise node_modules del contenedor
      - ./.wwebjs_auth:/workspace/.wwebjs_auth
      - ./camiones:/workspace/camiones

    environment:
      NODE_ENV: development
      CACHE_DIR: /workspace/camiones

    command: sleep infinity